---
- name: "Deploy eamonnmr.com"
  hosts: all
  become: true
  become_user: root
  tasks:

  - name: Install apt packages
    apt: name={{item}} state=installed update_cache=yes
    with_items:
    - "nginx"
    - "esl-erlang"
    - "inotify-tools"
    - "elixir"
    - "postgresql-client"
    - "postgresql"
    - "postgresql-contrib"

  - name: 
    copy: src=./ dest=/var/www
