---
- name: "Deploy eamonnmr.com"
  hosts: all
  become: true
  become_user: root
  tasks:

  - name: Install apt packages
    apt: name={{item}} state=installed update_cache=yes
    with_items:
    - "nginx"
    - "esl-erlang"
    - "inotify-tools"
    - "elixir"
    - "postgresql-client"
    - "postgresql"
    - "postgresql-contrib"

  - name: 
    copy: src=./ dest=/var/www

  - name:
    shell:
     >
       # Postgres: ALTER USER Postgres WITH PASSWORD 'postgres';
       # ecto.create
       #

  - name: Install mix stuff
    shell: >
      mix local.hex
      mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new.ez

  - name: NPM stuff
    shell: >
      npm install
      npm run build  
