---
- name: "Deploy eamonnmr.com"
  hosts: all
  become: true
  become_user: root
  tasks:

  - name: Install apt packages
    apt: name={{item}} state=installed update_cache=yes
    with_items:
    - "nginx"

  - name: Upload build to server
    copy: src=../build/ dest=/var/www/html

  - name: Upload server config
    copy: 

