---
- name: "Deploy Departure Board"
  hosts: all
  become: true
  become_user: root
  tasks:

  - name: Install apt packages
    apt: name={{item}} state=installed update_cache=yes
    with_items:
    - "nginx"

  - name: Upload build to server
    copy: src=../build/ dest=/var/www/html/

  - name: Upload server conf
    copy: src=etc/nginx/sites-enabled/departures.conf dest=/etc/nginx/sites-enabled/departures.conf

  - name: Ensure that new nginx config is applied
    service: name=nginx state=restarted
